### ISSUE TITLE
IPS_GetStatus ist nicht bekannt.

### ISSUE THREAD

**Issue by Nall-chan** [symcon/Assistant#20]
https://github.com/symcon/Assistant/blob/80dcb9bd0b8b289ac9cee1d7606377e35c92e035/Assistant/registry.php#L206
Eventuell gegen IPS_GetInstance ersetzen?
Siehe auch:
https://www.symcon.de/forum/showthread.php?p=399975

**Comment by paresy** [comment]
Fix in https://github.com/symcon/Assistant/commit/0d655709e0f202959a5f653f8a0faf6ef356afa2
